Bootstrap:docker  
From:centos:centos7.4.1708

%labels
MAINTAINER Thomas Green

%environment

%runscript
exec /bin/bash /bin/echo "Not supported"

%post  
yum install yum-utils
yum-config-manager --add-repo http://fluidityproject.github.com/yum/fluidity-rhel7-mpich
yum install fluidity
yum install fluidity-dev

